"""init_db

Revision ID: 63a5296ee01e
Revises: 
Create Date: 2019-09-26 15:30:01.537313

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '63a5296ee01e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pamm_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('currency', sa.JSON(), nullable=False),
        sa.Column('params', sa.JSON(), nullable=True),
        sa.Column('activated_at', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_accounts_status_code',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_investors_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_orders_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_orders_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_tickets_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_tickets_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_accounts_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('start_balance', sa.BigInteger(), nullable=False),
        sa.Column('last_balance', sa.BigInteger(), nullable=False),
        sa.Column('start_at', sa.Integer(), nullable=False),
        sa.Column('stop_at', sa.Integer(), nullable=False),
        sa.Column('status_code_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['pamm_accounts.id'], ),
        sa.ForeignKeyConstraint(['status_code_id'], ['pamm_accounts_status_code.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_investors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('start_amount', sa.BigInteger(), nullable=False),
        sa.Column('last_amount', sa.BigInteger(), nullable=False),
        sa.Column('last_percent', sa.Integer(), nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['pamm_accounts.id'], ),
        sa.ForeignKeyConstraint(['status_id'], ['pamm_investors_status.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('currency_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.BigInteger(), nullable=False),
        sa.Column('order_type_id', sa.Integer(), nullable=True),
        sa.Column('order_status_id', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['pamm_accounts.id'], ),
        sa.ForeignKeyConstraint(['order_status_id'], ['pamm_orders_status.id'], ),
        sa.ForeignKeyConstraint(['order_type_id'], ['pamm_orders_type.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pamm_tickets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('ticket_type_id', sa.Integer(), nullable=True),
        sa.Column('ticket_status_id', sa.Integer(), nullable=True),
        sa.Column('params', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['pamm_accounts.id'], ),
        sa.ForeignKeyConstraint(['ticket_status_id'], ['pamm_tickets_status.id'], ),
        sa.ForeignKeyConstraint(['ticket_type_id'], ['pamm_tickets_type.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pamm_tickets')
    op.drop_table('pamm_orders')
    op.drop_table('pamm_investors')
    op.drop_table('pamm_accounts_status')
    op.drop_table('pamm_tickets_type')
    op.drop_table('pamm_tickets_status')
    op.drop_table('pamm_orders_type')
    op.drop_table('pamm_orders_status')
    op.drop_table('pamm_investors_status')
    op.drop_table('pamm_accounts_status_code')
    op.drop_table('pamm_accounts')
    # ### end Alembic commands ###
